# Generated by Django 5.1.3 on 2024-11-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upvote',
            new_name='UpvotePosts',
        ),
    ]
