# Generated by Django 5.1.3 on 2024-11-27 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownvoteAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.ForeignKey(db_column='answerId', on_delete=django.db.models.deletion.CASCADE, to='users.answers')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'answerId'), name='unique_downvoteAnswer')],
                'unique_together': {('username', 'answerId')},
            },
        ),
        migrations.CreateModel(
            name='UpvoteAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerId', models.ForeignKey(db_column='answerId', on_delete=django.db.models.deletion.CASCADE, to='users.answers')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'answerId'), name='unique_upvoteAnswer')],
                'unique_together': {('username', 'answerId')},
            },
        ),
    ]
