# Generated by Django 5.1.3 on 2024-11-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_downvoteanswers_upvoteanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='downvoteCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='upvoteCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
