# Generated by Django 5.1.3 on 2024-11-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_upvote_upvoteposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='upvoteposts',
            name='postId',
            field=models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='users.post'),
        ),
        migrations.AlterField(
            model_name='upvoteposts',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
