# Generated by Django 5.1.3 on 2024-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_post_username_alter_upvoteposts_postid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvoteCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
