# Generated by Django 5.1.3 on 2024-11-26 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_upvotecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvoteposts',
            name='username',
            field=models.ForeignKey(db_column='username', default='alitariq', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
