# Generated by Django 5.1.3 on 2024-11-26 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_upvoteposts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
