# Generated by Django 5.1.3 on 2024-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvoteCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
