# Generated by Django 5.1.3 on 2024-11-26 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post_downvotecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvoteposts',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DownvotePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(db_column='postId', on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'postId'), name='unique_downvote')],
                'unique_together': {('username', 'postId')},
            },
        ),
    ]
